### PR TITLE
Translate UI to English

### LINKED ISSUE #30: Translate UI to English
**Is your feature request related to a problem? Please describe.**
External collaborators are having some difficulties with the Portuguese layout.

**Describe the solution you'd like**
The UI should be translated to English for the MVP.

**Describe alternatives you've considered**
#29

### PR DESCRIPTION
**Pull request by filipecorrea**
Fixes #30 

### Overview 

Screen Shot 2020-09-11 at 17 39 35

Screen Shot 2020-09-11 at 17 39 44

### CODE REVIEW

**Comment by camilasb** [comment]
@filipecorrea think the best wording for the fields are instead:
-Text to be reviewed OR Your text (literal from Portuguese)
-Reviewed text

-> Maybe buttons should be more descriptive as well

**Comment by crissm** [comment]
Similar comments, I suggest some update:
"Spoken language" ->  "Your Text" 
"Sign language" -> "Reviewed Text"
"Translate" -> "Review/Translate"

I'm also thinking if it would be a good idea to include a language dropdown where the user can select the language before insert the text. What do you think? @camilasb @filipecorrea

**Comment by filipecorrea** [comment]
@crissm Regarding https://github.com/IBM/libras-ui/pull/33#issuecomment-689915987, we'll work on that on https://github.com/IBM/libras-ui/issues/29.

**Comment by camilasb** [comment]
@filipecorrea i opened it locally, but i get the message 
image
and even after running `npm update` it doesnt work, showing me the same message still
do you have a screenshot in English so we can see the change then?

**Comment by filipecorrea** [comment]
Hi @camilasb. This is just a warning. You can ignore it and the application will start after a moment. Anyway the pull request description is updated with new screenshots.

**Pull request merged**
